### user api requests

###user regitration

post http://localhost:4000/user-api/user 
Content-Type: application/json

{
  "userType":"user",
  "username":"ravi",
  "password":"ravi",
  "email":"ravi@gmail.com"
}


###user login
post http://localhost:4000/user-api/login 
Content-Type: application/json

{
  "userType":"user",
  "username":"ravi",
  "password":"ravi"
}

###reading the articles of all the authors

get http://localhost:4000/user-api/books


###writing the comments
post http://localhost:4000/user-api/comment
Content-Type: application/json

{
  "bookId":"1718041647",
  "username":"ravi",
  "comment":"this book is good"
}



###
get http://localhost:4000/author-api/test-author


###
get http://localhost:4000/admin-api/test-admin